finding_advising_information:
  description: >
    Conduct a thorough research about the asked topic which is in this sentence: {topic}
    Make sure you find the relevant information.
  expected_output: >
    A precise answer about the very detail(s) asked about the Computer Science program.
  agent: computer_science_advisor
  async: true
  allow_delegation: true

finding_course:
  description: >
    Conduct a thorough research about the asked course(s) in this sentence: {topic}
    Make sure you find the relevant information.
  expected_output: >
    A precise answer about the very detail(s) asked about the course(s)
  agent: course_finder
  async: true
  allow_delegation: true

reporting:
  description: >
    Review the context you got and filter the final answer to only relevant information
    Make sure the report contains any and all relevant information.
  expected_output: >
    An answer with the main topics, each with very concrete information.
    Formatted as markdown without '```'
  agent: reporter
